FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build


FROM node:22-alpine

WORKDIR /app

COPY --from=build /app/dist/veterinary-frontend/browser ./public
COPY server.mjs ./server.mjs

USER node

EXPOSE 4200

CMD ["node", "server.mjs"]
