spring.application.name=owner-service
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3307/veterinary_owners?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info

app.auth.jwt-secret=${JWT_SECRET:01234567890123456789012345678901}